### ISSUE TITLE
Requirements and Feasibility Analysis "Bazelizing Open Image Denoise"

### ISSUE THREAD

**Issue by ghost** [Vertexwahn/rules_oidn#3]
(this is in context of the bounty https://app.bountysource.com/issues/117458567-black-stripes-in-denoised-image)

## Article

https://medium.com/@Vertexwahn/bazelizing-open-image-denoise-part-1-the-journey-begins-a16c78ea1b88

## Requirement "Bazel"

> Open Image Denoise: From CMake to Bazel
> The build system of Open Image Denoise is [CMake](https://cmake.org/). Instead of CMake I want to use Open Image Denoise  using [Bazel](https://bazel.build/). This requires to bazelize Open Image Denoise first.

* Is this a hard requirement (e.g. "absolutely non-disputable requirement) ?
* what are the main 3 reasons to use bazel / to not use Cmake?

## Feasibility
* The effort to use a non-supported (by the core team) build-system  for a C++ application can be excessive
  * Achieving the initial port can become a full-time problem
  * Maintenance (update to new versions) can become non-feasible

**Comment by ghost** [comment]
https://github.com/Vertexwahn/rules_oidn/issues/1#issuecomment-1464913690: Bazel is a MUST Requirement, closing.

**Comment by Vertexwahn** [comment]
There can be different reasons why someone Is using Bazel instead of CMake to Bazel. It depends on different things like project size, project type, etc.

- Caching: Bazel knows exactly which tests need to be re-executed when something has changed (e.g. modified source code or data file). This leads to significantly slower test times compared to CMake. This is important when doing test-driven development.
- Bazel is polyglot - it supports many other languages (such as Python, Rust, Go, Java, etc.) - that gives me the opportunity to combine my python scripts that generate my own weights in one build without having to switch build systems (there is same python support in CMake but that is far beyond what Bazel can do here -> for instance, there is Bazel Python Plugin for PyCharm)
- CMake Legacy: The CMake configuration language has a lot of legacy stuff - [Policies](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Policies.html) and Modern CMake guides help you to work around it - but the whole CMake "language" look somehow old and odd. Bazel has Starlark (python subset) and a clear concept and supports windows for deprecating old features.

**Comment by ghost** [comment]
As a sidenote: I do not like CMake personally. Inconsistencies start with naming:

* `CMake` => `cmake`
* `CMakeLists.txt` => `cmake.txt`
